<?php

    include('../admin_enrollment_header.php');
    include('../../enrollment/classes/StudentEnroll.php');
    require_once('../../admin/classes/AdminUser.php');

    if(!AdminUser::IsAuthenticated()){
        header("Location: /dcbt/adminLoggedIn.php");
        exit();
    }
    // TODO: 
    if(isset($_POST['create_teacher_btn'])){
        
        $enroll = new StudentEnroll($con);

        $createUrl = base_url . "/index.php";

        $firstname = $_POST['firstname'];
        $lastname = $_POST['lastname'];
        $department_id = $_POST['department_id'];
 
        // Autogenerated
        $password = 123456;
        $sql = $con->prepare("INSERT INTO teacher
            (firstname, lastname, department_id, password)
            VALUES(:firstname, :lastname, :department_id, :password)");
        
        $sql->bindValue(":firstname", $firstname);
        $sql->bindValue(":lastname", $lastname);
        $sql->bindValue(":department_id", $department_id);
        $sql->bindValue(":password", $password);
        $sql->execute();
        
    }
?>

<div class='col-md-8 row offset-md-1'>
    <h4 class='text-center mb-3'>Create Subject Schedule</h4>
    <form method='POST'>
            <div class="modal-body">
                <div class="row mb-3">
                    <div class="col-md-3">
                        <label for="firstname">Firstname</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" name="firstname" class="form-control">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">
                        <label for="strand-name">Lastname</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" name="lastname" class="form-control">
                    </div>
                </div>
                <div class="row mb-3">
                <label for="strand-name" class="col-sm-2 col-form-label">Department</label>
                <div class="col-sm-10">
                    <select  style="width: 349px; margin-left:45px;" class="form-select" name="department_id" aria-label="Select strand name">
                    <option selected>Choose Department</option>
                    <option value="4">Senior High School</option>
                    </select>
                </div>
                </div>




            </div>

            <div class="modal-footer">
                <button name="create_teacher_btn" type="submit" class="btn btn-primary">Save</button>
            </div>
    </form>
</div>
 